export interface IPatientNew {
    fullName: string,
    gender: string,
    age: number,
    referringDoctor?: string,
    referringMedicalOrganization?: string,
    isCHFConfirmed: boolean,
    dateDiagnosisCHF: Date,
    wasHospitalised: boolean,
    preferentialDrugs: "no" | "yes" | "ssz",
    note?: string,
    snils: number,
    address: string,
    phoneNumber: string,
    MISCardNumber: number,
    dateBirth: Date,
    relative?: string,
    dateDeath?: Date,
    relativePhoneNumber?: string,
}