export interface IPatientNew {
    name: string,
    last_name: string,
    patronymic: string,
    gender: string,
    age: number,
    birth_date: Date,
    dod?: Date,
    location: "NSO" | "Novosibirsk" | "other",
    district: string,
    address: string,
    phone: number,
    patient_note?: string,
    referring_doctor?: string,
    referring_clinic_organization?: string,
    disability: "no" | "I" | "II" | "III" | "refusal",
    lgota_drugs: "no" | "yes" | "ssz",
    has_hospitalization: boolean,
    count_hospitalization: number,
    last_hospitalization_date: Date,
}